_wandb:
    value:
        cli_version: 0.23.1
        e:
            rrtkgw72ni2dsqs3jxr9aa2skj9r4drf:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "3221225472"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "795972657152"
                email: lishuyustevenli@163.com
                executable: /Users/lishuyu/miniconda3/bin/python
                host: 10-20-127-83.dynapool.wireless.nyu.edu
                memory:
                    total: "25769803776"
                os: macOS-26.0.1-arm64-arm-64bit-Mach-O
                program: /Users/lishuyu/Codes/wandbTestCNN/train.py
                python: CPython 3.13.9
                root: /Users/lishuyu/Codes/wandbTestCNN
                startedAt: "2025-12-04T23:32:50.829341Z"
                writerId: rrtkgw72ni2dsqs3jxr9aa2skj9r4drf
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 16
            "4": 3.13.9
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 64
epochs:
    value: 5
log_samples:
    value: false
lr:
    value: 0.001
project:
    value: wandb-mnist-demo
wandb_mode:
    value: online
